a= int(input("첫 번째 정수 : "))
b= int(input("두 번째 정수 : "))

print(a, "**", b, "=", (a**b))
print(a, "+", b, "=", (a+b))
print(a, "-", b, "=", (a-b))
print(a, "*", b, "=", (a*b))
print(a, "/", b, "=", (a/b))
print(a, "%", b, "=", (a%b))
print(a, "//", b, "=", (a//b))
